### ISSUE TITLE
Add AKS cost optimization demo 

### ISSUE THREAD

**Issue by MarcusFelling** [microsoft/contosotraders-cloudtesting#226]
## Tasks

- [x] Parameterize AKS deployment manifest: `cpu`, `mem`, `replicas`
- [x] EnvSubst these parameters using: 
  - [x] GH action
  - [x] AZD pipeline task
- [x] New AZD pipeline: matrix strategy
- [x] New GH workflow: matrix strategy
- [x] New demo script

## Open Questions

- [x] How do we "reset" the AKS cluster once all these load tests have concluded?
- [x] Do we need a new load test? Or can we reuse the existing one (targeting product API) 
- [x] New pass/fail critiera needed? 
- [x] Decide if it makes sense to merge new pipelines with main pipelines (release criteria?)
- [x] Need to figure out cost/billing impact to users:
  - [x] GH action minutes
  - [x] AZD pipeline minutes
  - [x] Azure billing from load test runs

## Decisions

1. These load tests for cost-optimization/right-sizing can also be performed against ACA too (and not just AKS). But given that ACA metrics are [currently not ingestable into Azure Load Testing](https://learn.microsoft.com/en-us/azure/load-testing/resource-supported-azure-resource-types#supported-azure-resource-types), diagnosing failures will be painful for the users. 
   - For now, let's just skip ACA entirely, and focus on AKS. 
   - ACA support is in [on the Load testing team's backlog](https://github.com/microsoft/azure-load-testing/issues/129#issuecomment-1367938772). Let's revisit this in the future once support is enabled. 

## Reference Links

- [aka.ms/MALT-AKSdemo](https://aka.ms/MALT-AKSdemo)
- Simulating pairwise combinatorics in az pipeline 👀
  - [https://stackoverflow.com/a/72676056](https://stackoverflow.com/a/72676056)
  - [https://stackoverflow.com/a/62891569](https://stackoverflow.com/a/62891569)
